
github:
    client_id: 1c75ca03819618318430

    github:
      client_secret: 65d2de4738d2a0ac8bf110427d0a60fa448d662a

        github:
          redirect_uri: http://localhost:8080/callback

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cummunity?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
#    username: root
#    password: root

